### ISSUE TITLE
Disable `Diagram selects Text` for klighd-cli

### ISSUE THREAD

**Issue by Skgland** [kieler/klighd-vscode#58]
Currently the `Diagram selects Text` option is available and enabled by default for the klighd-cli.
This option is not useful there as there is no text.
It also causes a NullPointerException in the Language Server when selecting elements (Language Server keeps working so non-fatal).

<details>
<summary>Console Log</summary>

```
[LSP on Port 57426] 12762 [pool-2-thread-1] ERROR t.ide.server.concurrent.ReadRequest  - Error during request: 
java.lang.NullPointerException
	at org.eclipse.xtext.ide.server.Document.getPosition(Document.java:66)
	at org.eclipse.sprotty.xtext.DiagramSelectionListener.lambda$selectionChanged$0(DiagramSelectionListener.java:85)
	at org.eclipse.sprotty.xtext.tracing.XtextTraceProvider.lambda$withSource$0(XtextTraceProvider.java:104)
	at org.eclipse.xtext.ide.server.LanguageServerImpl$1.lambda$null$0(LanguageServerImpl.java:1099)
	at org.eclipse.xtext.ide.server.WorkspaceManager.doRead(WorkspaceManager.java:438)
	at org.eclipse.xtext.ide.server.LanguageServerImpl$1.lambda$doRead$1(LanguageServerImpl.java:1098)
	at org.eclipse.xtext.ide.server.concurrent.ReadRequest.lambda$doRun$0(ReadRequest.java:66)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
</details>

**Comment by NiklasRentzCAU** [comment]
The language server no longer throws an exception for this, so the visible issue has been resolved. Furthermore, we cannot easily figure out if we are in the CLI or the VS Code realm here. Closing as won't fix.
